#
# Makefile for cleanup of sources for the compilation of a single PDF
# of the entire series of Lecture Notes in Electromagnetic Theory II,
# Uppsala University, 2022--2025.
#
# Copyright (C) 2025 under GPL 3.0, Fredrik Jonsson
#
all:
	@echo "Run 'make clean' to clean directory from temporary files."

clean:
	rm -Rf *~
