#
# Makefile for cleanup of sources for the World Map of Electromagnetics
# in the series of Lecture Notes in Electromagnetic Theory II, Uppsala
# University, 2022--2026.
#
# Copyright (C) 2026 under GPL 3.0, Fredrik Jonsson
#
all:
	@echo "Run 'make clean' to clean directory from temporary files."

clean:
	rm -Rf *~
